services:
  - type: web
    name: crypto-macd-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        value: https://crypto-macd-bot.onrender.com
